# Stop Summary Check Hook
# Reminds about implementation closeout checklist when task appears to be finishing

Write-Host ""
Write-Host "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
Write-Host "✓ Task appears to be ending. Closeout checklist:"
Write-Host "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
Write-Host ""
Write-Host "Before wrapping up, ensure:"
Write-Host ""
Write-Host "📋 Deliverables:"
Write-Host "   □ Changed files listed"
Write-Host "   □ Commits summarized"
Write-Host "   □ Scope boundaries clear"
Write-Host ""
Write-Host "✅ Validations:"
Write-Host "   □ Docs validation: PASS / WARNING / FAIL / NOT RUN"
Write-Host "   □ Unity compile: PASS / FAIL / NOT RUN (with reason)"
Write-Host "   □ Log scan: PASS / FAIL / NOT RUN (with reason)"
Write-Host "   □ Non-regression: PASS / WARNING / FAIL"
Write-Host "   □ Play Mode: NOT RUN (sandbox) / reason"
Write-Host ""
Write-Host "📝 Documentation:"
Write-Host "   □ Spec moved to implementados/ (if complete)"
Write-Host "   □ PROJECT_LOG.md updated"
Write-Host "   □ IMPLEMENTATION_STATUS.md updated (if status changed)"
Write-Host "   □ Docs validation run and PASS"
Write-Host ""
Write-Host "⚠️  Pending & Risk:"
Write-Host "   □ Pending items listed (if any)"
Write-Host "   □ Residual risks documented (if any)"
Write-Host ""
Write-Host "🚫 DO NOT:"
Write-Host "   □ Execute git push (awaits user approval)"
Write-Host "   □ Open PR/MR (awaits user approval)"
Write-Host "   □ Hide validation failures"
Write-Host "   □ Claim compliance without evidence"
Write-Host ""
Write-Host "→ If all checks ✓, ready to deliver to user"
Write-Host ""
Write-Host "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
Write-Host ""

exit 0
