# Test Scenario Required Guard
#
# Checks if a human test scenario file exists when runtime/gameplay changes detected.
# Reads change-scope.json (generated by detect-change-scope.ps1) and verifies corresponding
# test scenario in docs/05_VALIDATION/playmode/<spec_id>_human_test_scenario.md.
#
# Status: DISABLED (manual trigger)
# Rationale: Helps ensure Phase 3 deliverables are documented before /finish-spec closeout

param(
    [string]$SpecId,
    [string]$ChangeScopeJsonPath = "$PSScriptRoot/../change-scope.json"
)

function Test-TestScenarioRequired {
    param(
        [string]$SpecId,
        [string]$ChangeScopeJsonPath
    )

    # If no change scope detected, skip check
    if (-not (Test-Path $ChangeScopeJsonPath)) {
        Write-Host "[INFO] test-scenario-required-guard: change-scope.json not found, skipping check" -ForegroundColor Cyan
        return $true
    }

    try {
        $changeScope = Get-Content $ChangeScopeJsonPath | ConvertFrom-Json
    } catch {
        Write-Host "[WARN] test-scenario-required-guard: Could not parse change-scope.json: $_" -ForegroundColor Yellow
        return $true  # Do not block on parse error
    }

    # Determine if runtime/gameplay changes detected
    $isRuntime = $changeScope.runtime_changes -eq $true -or `
                 $changeScope.gameplay_changes -eq $true -or `
                 $changeScope.ui_changes -eq $true -or `
                 $changeScope.cave_changes -eq $true -or `
                 $changeScope.combat_changes -eq $true -or `
                 $changeScope.save_changes -eq $true -or `
                 $changeScope.event_changes -eq $true

    if (-not $isRuntime) {
        Write-Host "[INFO] test-scenario-required-guard: No runtime/gameplay changes detected, test scenario not required" -ForegroundColor Cyan
        return $true
    }

    # Check if test scenario file exists
    $testScenarioPath = Join-Path (Split-Path $ChangeScopeJsonPath) "docs/05_VALIDATION/playmode/$($SpecId)_human_test_scenario.md"

    if (Test-Path $testScenarioPath) {
        Write-Host "[PASS] test-scenario-required-guard: Test scenario found at $testScenarioPath" -ForegroundColor Green
        return $true
    } else {
        Write-Host "[WARN] test-scenario-required-guard: Runtime/gameplay changes detected but NO test scenario found" -ForegroundColor Yellow
        Write-Host "[WARN]   Expected: $testScenarioPath" -ForegroundColor Yellow
        Write-Host "[WARN]   Action: Invoke /gameplay-test-scenario skill to create test scenario before /finish-spec" -ForegroundColor Yellow
        return $false
    }
}

# Run guard
$result = Test-TestScenarioRequired -SpecId $SpecId -ChangeScopeJsonPath $ChangeScopeJsonPath
exit $(if ($result) { 0 } else { 1 })
